FROM mrc.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ../
RUN dotnet restore "ShelkovyPut_Main.csproj"

COPY ./Application ./Application/
COPY ./Domain ./Domain/
COPY ./Infrastructure ./Infrastructure/
RUN dotnet build "ShelkovyPut_Main.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ShelkovyPut_Main.csproj" -c Release -o /app/publish

FROM mrc.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=publish /app/publish
ENTRYPOINT ["dotnet", "ShelkovyPut_Main.dll"]